/**
 * Supplier Search & Multi-Select Panel — L1-14 visualization in SaaS.
 *
 * Search bar with dropdown results for selecting multiple suppliers.
 * Selected suppliers shown as removable tags. Graph highlights the union
 * of all selected suppliers' impact:
 *   1. supplied_nodes — nodes these suppliers feed
 *   2. affected_products — end products reachable via backward trace
 *   3. the full upstream chain between them (computed in GraphView)
 *
 * After key.scaf restore: shows real supplier names instead of hashes.
 */

import { useMemo, useState, useRef, useEffect } from "react";
import { useScaffold, useDispatch } from "../context/ScaffoldContext";

interface SupplierInfo {
  hash: string;
  label: string;
  suppliedCount: number;
  impactCount: number;
  suppliedNodes: string[];
  affectedProducts: string[];
}

export function SupplierImpactView() {
  const { data, selectedSuppliers, keyData } = useScaffold();
  const dispatch = useDispatch();
  const [searchTerm, setSearchTerm] = useState("");
  const [dropdownOpen, setDropdownOpen] = useState(false);
  const wrapperRef = useRef<HTMLDivElement>(null);

  // Close dropdown when clicking outside
  useEffect(() => {
    function handleClickOutside(e: MouseEvent) {
      if (wrapperRef.current && !wrapperRef.current.contains(e.target as Node)) {
        setDropdownOpen(false);
      }
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  const suppliers = useMemo(() => {
    if (!data?.suppliers) return [];

    const list: SupplierInfo[] = [];
    for (const [hash, info] of Object.entries(data.suppliers)) {
      const restoredName = keyData?.suppliers?.[hash];
      list.push({
        hash,
        label: restoredName ?? hash.slice(0, 12) + "...",
        suppliedCount: info.supplied_nodes.length,
        impactCount: info.impact_count,
        suppliedNodes: info.supplied_nodes,
        affectedProducts: info.affected_products,
      });
    }

    // Sort by impact count descending (most critical first)
    list.sort((a, b) => b.impactCount - a.impactCount);
    return list;
  }, [data, keyData]);

  // Filter suppliers by search term for the dropdown
  const filteredSuppliers = useMemo(() => {
    if (!searchTerm) return suppliers;
    const q = searchTerm.toLowerCase();
    return suppliers.filter(
      (s) =>
        s.label.toLowerCase().includes(q) ||
        s.hash.toLowerCase().includes(q),
    );
  }, [suppliers, searchTerm]);

  // Build node label lookup for displaying supplied part@site
  const nodeLabel = useMemo(() => {
    const map = new Map<string, string>();
    if (!data?.nodes) return map;
    for (const nodeId of Object.keys(data.nodes)) {
      const restored = keyData?.nodes?.[nodeId];
      map.set(
        nodeId,
        restored ? `${restored.part}@${restored.site}` : nodeId.slice(0, 8),
      );
    }
    return map;
  }, [data, keyData]);

  // Aggregate detail info for all selected suppliers
  const selectedDetails = useMemo(() => {
    if (selectedSuppliers.size === 0) return null;
    const suppliedNodes = new Set<string>();
    const affectedProducts = new Set<string>();
    for (const hash of selectedSuppliers) {
      const sup = suppliers.find((s) => s.hash === hash);
      if (sup) {
        sup.suppliedNodes.forEach((n) => suppliedNodes.add(n));
        sup.affectedProducts.forEach((n) => affectedProducts.add(n));
      }
    }
    return {
      suppliedNodes: Array.from(suppliedNodes),
      affectedProducts: Array.from(affectedProducts),
    };
  }, [selectedSuppliers, suppliers]);

  // Selected supplier objects for tags display
  const selectedList = useMemo(
    () => suppliers.filter((s) => selectedSuppliers.has(s.hash)),
    [suppliers, selectedSuppliers],
  );

  const hasSuppliers = suppliers.length > 0;

  return (
    <div className="sidebar-section">
      <h3>Suppliers{hasSuppliers ? ` (${suppliers.length})` : ""}</h3>

      {!hasSuppliers ? (
        <div className="supplier-empty">
          <p>No supplier data available.</p>
          <p className="supplier-empty-hint">
            Supplier data is generated by the Local Tool's impact analysis
            (L1-14). Re-run the pipeline with Supplier Map data to populate
            this panel.
          </p>
        </div>
      ) : (
        <>
          {/* Search bar with dropdown multi-select */}
          <div className="supplier-multiselect" ref={wrapperRef}>
            <div className="supplier-search">
              <input
                type="text"
                placeholder="Search suppliers..."
                value={searchTerm}
                onChange={(e) => {
                  setSearchTerm(e.target.value);
                  setDropdownOpen(true);
                }}
                onFocus={() => setDropdownOpen(true)}
              />
            </div>

            {/* Dropdown results */}
            {dropdownOpen && (
              <div className="supplier-dropdown">
                {filteredSuppliers.length === 0 ? (
                  <div className="supplier-no-match">
                    No suppliers match &ldquo;{searchTerm}&rdquo;
                  </div>
                ) : (
                  filteredSuppliers.map((sup) => (
                    <label
                      key={sup.hash}
                      className={`supplier-dropdown-item ${selectedSuppliers.has(sup.hash) ? "checked" : ""}`}
                    >
                      <input
                        type="checkbox"
                        checked={selectedSuppliers.has(sup.hash)}
                        onChange={() =>
                          dispatch({ type: "TOGGLE_SUPPLIER", payload: sup.hash })
                        }
                      />
                      <span className="supplier-dropdown-label">{sup.label}</span>
                      <span className="badge">
                        {sup.impactCount} products · {sup.suppliedCount} nodes
                      </span>
                    </label>
                  ))
                )}
              </div>
            )}
          </div>

          {/* Selected supplier tags */}
          {selectedList.length > 0 && (
            <div className="supplier-tags">
              {selectedList.map((sup) => (
                <span key={sup.hash} className="supplier-tag">
                  {sup.label}
                  <button
                    className="supplier-tag-remove"
                    onClick={() =>
                      dispatch({ type: "TOGGLE_SUPPLIER", payload: sup.hash })
                    }
                    aria-label={`Remove ${sup.label}`}
                  >
                    ×
                  </button>
                </span>
              ))}
              {selectedList.length > 1 && (
                <button
                  className="supplier-clear-all"
                  onClick={() => dispatch({ type: "CLEAR_SUPPLIERS" })}
                >
                  Clear all
                </button>
              )}
            </div>
          )}

          {/* Detail panel for selected suppliers */}
          {selectedDetails && (
            <div className="supplier-detail">
              <h4>Supplied Nodes ({selectedDetails.suppliedNodes.length})</h4>
              <div className="supplier-detail-list">
                {selectedDetails.suppliedNodes.map((nodeId) => (
                  <div
                    key={nodeId}
                    className="supplier-detail-item supplied"
                  >
                    {nodeLabel.get(nodeId) ?? nodeId.slice(0, 8)}
                  </div>
                ))}
              </div>
              <h4>Affected End Products ({selectedDetails.affectedProducts.length})</h4>
              <div className="supplier-detail-list">
                {selectedDetails.affectedProducts.map((nodeId) => (
                  <div
                    key={nodeId}
                    className="supplier-detail-item affected"
                  >
                    {nodeLabel.get(nodeId) ?? nodeId.slice(0, 8)}
                  </div>
                ))}
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}
